PKG_NAME="fftw"
PKG_VERSION="3.3.9"
PKG_SHA256="bf2c7ce40b04ae811af714deb512510cc2c17b9ab9d6ddcf49fe4487eea7af3d"
PKG_LICENSE="GPL"
PKG_SITE="http://fftw.org"
PKG_URL="http://fftw.org/fftw-${PKG_VERSION}.tar.gz"
PKG_DEPENDS_HOST="toolchain:host"
PKG_DEPENDS_TARGET="toolchain"
PKG_CMAKE_OPTS_TARGET="-DENABLE_FLOAT=ON"
PKG_LONGDESC="FFTW is a C subroutine library for computing the discrete Fourier transform"
